services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Amazing\Media2click\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Amazing\Media2click\EventListener\IsContentUsedListener:
    tags:
      - name: event.listener
        identifier: 'm2cIsContentUsedListener'

